---
title: "test_package"
author: "Maria Henriquez"
date: "12/14/2020"
output: html_document
---

```{r load-packages}
# general preprocessing
library(tidyverse) # for data wrangling
library(lubridate) # for datetime
library(latticeExtra) # for adding the facet_grid
library(pracma) # for numerical functions
library(ggrepel)
library(gridExtra)
library(gluvarpro)
```


```{r}
readfile <- function(filename) {
  df_CGM <- read.csv(filename, 
                     header = TRUE, stringsAsFactors = FALSE)
  
  df_CGM <- data.frame(df_CGM$Timestamp..YYYY.MM.DDThh.mm.ss.,
                       df_CGM$Glucose.Value..mg.dL.)
  colnames(df_CGM) <- c("Time", "glucose")
  df_CGM$Time <- as.POSIXct(df_CGM$Time, format = "%Y-%m-%dT%H:%M:%OS", origin = "1970-01-01")
  df_CGM <- df_CGM %>%
    mutate(Date = date(Time)) %>%
    mutate(time_of_day = hms::as_hms(Time)) %>%
    mutate(type_of_event = ifelse(glucose > 180, 1, ifelse(glucose < 70, -1, 0))) # threshold and label is for hyper-/hypoglycemia identification
  
  return(tail(df_CGM, -11))
}
```

```{r plot-CGM, fig.height = 10, fig.width = 20}
plot_glucose <- function(df_CGM) {
  ggplot(df_CGM) +
  geom_point(data = df_CGM, aes(x = time_of_day, y = glucose),
             col = "orange", cex = 0.5) +
  geom_line(data = df_CGM, aes(x = time_of_day, y = glucose),
            col = "orange") +
  facet_grid(Date ~ ., scale = "fixed") +
  theme_bw() +
  ylab("Glucose Level") +
  xlab("Time of Day") +
  labs(title = "CGM data for Participant #1")
}

```

```{r}
interdaycv <- function(df) {
  cvx = (std(df$glucose) / mean(df$glucose)) * 100
  return(cvx)
}
```

```{r}
interdaysd <- function(df) {
  interdaysd = std(df$glcuose)
  return(interdaysd)
}
```

```{r}
TIR <- function(df, sd = 1, sr = 5) {
up = mean(df$glucose) + sd*std(df$glucose)
dw = mean(df$glucose) - 1*std(df$glucose)
TIR = nrow(filter(df, glucose <= up | glucose >= dw)) * sr
return(TIR)
}

```


```{r}
TOR <- function(df, sd = 1, sr = 5) {
up = mean(df$glucose) + sd*std(df$glucose)
dw = mean(df$glucose) - 1*std(df$glucose)
TOR = nrow(filter(df, glucose >= up | glucose <= dw)) * sr
return(TOR)
}
```

```{r}
POR <- function(df, sd = 1, sr = 5) {
up = mean(df$glucose) + sd*std(df$glucose)
dw = mean(df$glucose) - 1*std(df$glucose)
TOR = nrow(filter(df, glucose >= up | glucose <= dw)) * sr
POR = (TOR/(nrow(df)*sr))*100
return(POR)
}

```


```{r}
MGE <- function(df) {
  up = mean(df$glucose) + std(df$glucose)
  dw = mean(df$glucose) - std(df$glucose)
  MAGE = mean(filter(df, glucose >= up | glucose <= dw)$glucose)
  return(MAGE)

}
```

```{r}
MAGE <- function(df) {
  #TBD
}
```

```{r}
J_index <- function(df) {
  J = 0.001*((mean(df$glucose) + std(df$glucose))*2)
  return(J)
}
```

```{r}
GMI <- function(df) {
  GMI = 3.31 + (0.02392*mean(df$glucose))
  return(GMI)
}
```

```{r}
eA1c <- function(df) {
  eA1c = (46.7 + mean(df$glucose))/28.7
  return(eA1c)
}
```

```{r}

```

```{r}
summary_glucose <- function(df) {
  meanG = mean(df$glucose)
  medianG = median(df$glucose)
  minG = min(df$glucose)
  maxG = max(df$glucose)
  Q1G = quantile(df$glucose, 0.25)
  Q3G = quantile(df$glucose, 0.75)
  
  return(data.frame(meanG,
                    medianG,
                    minG,
                    maxG,
                    Q1G,
                    Q3G))
  
}
```

```{r}
summary_glucose(df_CGM)
```

```{r}
LGBI_HBGI <- function(df) {
f = data.frame(log_glucose = log(df$glucose^1.084) - 5.381)
f <- mutate(f, 
            rl = case_when(
              log_glucose <= 0 ~
                22.77*(log_glucose^2),
              TRUE ~ 0),
            rh = case_when(
              log_glucose > 0 ~
                22.77*(log_glucose^2),
              TRUE ~ 0)
            )

LGBI = mean(f$rl)
HGBI = mean(f$rh)

return(data.frame(LGBI, HGBI))

}


LGBI_HBGI(df_CGM)
```

```{r}
LGBI <- function(df) {
  f = data.frame(log_glucose = log(df$glucose^1.084) - 5.381)
f <- mutate(f, 
            rl = case_when(
              log_glucose <= 0 ~
                22.77*(log_glucose^2),
              TRUE ~ 0))

return(mean(f$rl))
  
}

```

```{r}
HGBI <- function(df) {
  f = data.frame(log_glucose = log(df$glucose^1.084) - 5.381)
f <- mutate(f, 
            rh = case_when(
              log_glucose > 0 ~
                22.77*(log_glucose^2),
              TRUE ~ 0))

return(mean(f$rh))
  
}

```




## TO DO:

- intradaysd
- intradaycv
- MAGE
- ADRR

SCARY
- uniquevalfilter
- MODD
- CONGA24









